### ISSUE TITLE
Alert notices are landing on offcanvas

### ISSUE THREAD

**Issue by wpre** [bootscore/bootscore#35]
There is a small bug in my-account (woocommerce) page. Some alert notices are landing on offcanvas. You can test it when you fill in for example the billing address fields and leave a required field blank. After save, the notices show up on offcanvas.

**Comment by crftwrk** [comment]
Thank you for reporting, this is a known issue. Offcanvas uses same hook for alerts like the account page. In case if you edit something in your account, it can be that an alert is shown in offcanvas instead in the top of the page. The alert in offcanvas is neccessary for feedback if you do a wrong login or registration in offcanvas.

For us so far, the benefit of using offcanvas login and dashboard is much more higher than the bug with the alerts on account page. We are planning to general refactor the WooCommerce alerts handling in bootScore, but this has a minor priority.

## Using default WC login

You can hotfix that very easy by using the default WooCommerce login and dashboard instead of offcanvas.

### Delete user offcanvas

Open `header.php` in your child, search for following snippet and delete it:

```php
<!-- offcanvas user -->
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvas-user">
  <div class="offcanvas-header bg-light">
    <span class="h5 mb-0"><?php esc_html_e('Account', 'bootscore'); ?></span>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="my-offcancas-account">
      <?php include get_template_directory() . '/woocommerce/myaccount/my-account-offcanvas.php'; ?>
    </div>
  </div>
</div>
```

### Change the user `<button>` to an `<a>` and link it to the `my-account` page.

Search in `header.php` for the user offcanvas toggler:

```php
<!-- User Toggler -->
<button class="btn btn-outline-secondary ms-1 ms-md-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvas-user" aria-controls="offcanvas-user">
  <i class="fas fa-user"></i>
</button>
```

Replace toggler with this:

```php
<!-- User Toggler -->
<a href="[my-account]" class="btn btn-outline-secondary ms-1 ms-md-2">
  <i class="fas fa-user"></i>
</a>
```

**Comment by crftwrk** [comment]
An idea is to generally remove alerts in offcanvas and do a redirect to `my-account.php` if login failed instead. 
Found something here: https://github.com/woocommerce/woocommerce/issues/11864

```php
// Redirect to my-account if offcanvas login failed
add_action( 'woocommerce_login_failed', 'redirect_on_login_failed' , 10, 0 );
function redirect_on_login_failed() : void {
  // Logout user doesn't have session, we need this to display notices
  if ( ! WC()->session->has_session() ) {
    WC()->session->set_customer_session_cookie( true );
  }
  wp_redirect( wp_validate_redirect( wc_get_page_permalink( 'myaccount' ) ) );
    exit;
}

// Redirect to home on logout (optional)
add_action('wp_logout','auto_redirect_after_logout');
function auto_redirect_after_logout(){
  wp_redirect( home_url() );
  exit();
}
```

If user login in checkout page, it redirects to `myaccount` as well. Anyone have a better idea? 

### ToDo
- [ ] Remove hook in `my-account-offcanvas.php`
- [ ] Remove jQuery to keep offcanvas open in `woocommerce/js/woocommerce.js`
- [ ] Add redirect snippet to `woocommerce-functions.php`

@Axos11 What do you think?
